on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.4
    
    - name: 📂 Sync themes
      uses: hrsetyono/git-sftp-action@v4.0.1
      with:
        url: "sftp://sftp.flywheelsites.com/joshuacook13/journey-church-3-0/wp-content/themes"
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        syncroot: '/wp-content/themes'
    - name: 📂 Sync plugins
      uses: hrsetyono/git-sftp-action@v4.0.1
      with:
        url: "sftp://sftp.flywheelsites.com/joshuacook13/journey-church-3-0/wp-content/plugins"
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        syncroot: '/wp-content/plugins'